#! /bin/bash

set -e

TANG_PORT=${TANG_PORT:-80}

DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ "$DIR" == "/tang" ]];
then
	TANG_INSIDE_DOCKER=true
fi

if [[ "${TANG_INSIDE_DOCKER-}" == "" ]];
then
    # Not inside a tang container.
    ARGS=()
    ARGS+=(-i -t)                      # Interactive, terminal
    ARGS+=(-p 0.0.0.0:$TANG_PORT:8080) # Poke hole
    ARGS+=(-v $DIR:/tang)              # Mount $PWD into /tang
    ARGS+=(-e TANG_INSIDE_DOCKER=YES)  # So that we don't recurse
    ARGS+=(-e GITHUB_USER=$GITHUB_USER)
    ARGS+=(-e GITHUB_PASSWORD=$GITHUB_PASSWORD)

    docker run "${ARGS[@]}" tang "$@"
    exit 0
fi

# So that go install can find it
mkdir -p /usr/src/github.com/scraperwiki
ln -sT /tang /usr/src/github.com/scraperwiki/tang

./install-tang

echo "Running tang..."
exec tang "$@"
